buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.setup]
nixPkgs = ["nodejs_22", "pnpm-9_x", "openssl"]
# taken from https://lazamar.co.uk/nix-versions/?channel=nixpkgs-unstable&package=nodejs to specify a minor version of node
nixpkgsArchive = '21808d22b1cda1898b71cf1a1beb524a97add2c4'
